
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentMap;

/**
* Project #2 CS2210
*
* @author Nathan O'Neel
* @version 1.0
* ©Copyright Cedarville University, its Computer Science faculty, and the 
* authors. All rights reserved.
* 
* File: Project2.java
* Created: Sept 2018
* Summary of Modifications:
*
* Description: This is Project #2 for CS2210 it is a GUI of that wraps Factorial and GCD
*/
import CryptoClasses.CharCount;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
public class MonoAlphabetCrypto extends javax.swing.JFrame {
    private CharCount[] sampleFrequency = new CharCount[26];
    private CharCount[] encryptedFrequency = new CharCount[26];
    Map<Character, Character> decryptKey = new HashMap<Character, Character>();
    Map<String, Integer> samplePairFrequency = new HashMap<String, Integer>();
    Map<String, Integer> encryptedPairFrequency = new HashMap<String, Integer>();
    String encryptedText = "";
    String sampleText = "";        
    /**
     * Creates new form Project2
     */
    public MonoAlphabetCrypto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        A_Value = new javax.swing.JTextField();
        A_Count = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B_Value = new javax.swing.JTextField();
        B_Count = new javax.swing.JLabel();
        C_Value = new javax.swing.JTextField();
        C_Count = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        D_Value = new javax.swing.JTextField();
        D_Count = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        E_Value = new javax.swing.JTextField();
        E_Count = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        J_Value = new javax.swing.JTextField();
        I_Value = new javax.swing.JTextField();
        H_Value = new javax.swing.JTextField();
        G_Value = new javax.swing.JTextField();
        F_Value = new javax.swing.JTextField();
        F_Count = new javax.swing.JLabel();
        G_Count = new javax.swing.JLabel();
        H_Count = new javax.swing.JLabel();
        I_Count = new javax.swing.JLabel();
        J_Count = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        B9 = new javax.swing.JLabel();
        B10 = new javax.swing.JLabel();
        M_Value = new javax.swing.JTextField();
        L_Value = new javax.swing.JTextField();
        K_Value = new javax.swing.JTextField();
        K_Count = new javax.swing.JLabel();
        L_Count = new javax.swing.JLabel();
        M_Count = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        B16 = new javax.swing.JLabel();
        B15 = new javax.swing.JLabel();
        B17 = new javax.swing.JLabel();
        B18 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        B19 = new javax.swing.JLabel();
        B21 = new javax.swing.JLabel();
        B20 = new javax.swing.JLabel();
        B22 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        B23 = new javax.swing.JLabel();
        Z_Value = new javax.swing.JTextField();
        Y_Value = new javax.swing.JTextField();
        X_Value = new javax.swing.JTextField();
        W_Value = new javax.swing.JTextField();
        V_Value = new javax.swing.JTextField();
        U_Value = new javax.swing.JTextField();
        T_Value = new javax.swing.JTextField();
        S_Value = new javax.swing.JTextField();
        R_Value = new javax.swing.JTextField();
        P_Value = new javax.swing.JTextField();
        O_Value = new javax.swing.JTextField();
        N_Value = new javax.swing.JTextField();
        N_Count = new javax.swing.JLabel();
        O_Count = new javax.swing.JLabel();
        P_Count = new javax.swing.JLabel();
        R_Count = new javax.swing.JLabel();
        S_Count = new javax.swing.JLabel();
        T_Count = new javax.swing.JLabel();
        U_Count = new javax.swing.JLabel();
        V_Count = new javax.swing.JLabel();
        W_Count = new javax.swing.JLabel();
        X_Count = new javax.swing.JLabel();
        Y_Count = new javax.swing.JLabel();
        Z_Count = new javax.swing.JLabel();
        B25 = new javax.swing.JLabel();
        Q_Value = new javax.swing.JTextField();
        Q_Count = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DecryptedText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        EncryptedText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        SampleText = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        ReadSample = new javax.swing.JButton();
        Decrypt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadSampleText = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A.setText("A");

        A_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A_Value.setText("A");
        A_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_ValueActionPerformed(evt);
            }
        });

        A_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_Count.setText("A Count");

        B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B1.setText("B");

        B_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        B_Value.setText("B");
        B_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ValueActionPerformed(evt);
            }
        });

        B_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_Count.setText("B Count");

        C_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        C_Value.setText("C");
        C_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_ValueActionPerformed(evt);
            }
        });

        C_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_Count.setText("C Count");

        B2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B2.setText("C");

        D_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D_Value.setText("D");
        D_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_ValueActionPerformed(evt);
            }
        });

        D_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_Count.setText("D Count");

        B3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B3.setText("D");

        E_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        E_Value.setText("E");
        E_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_ValueActionPerformed(evt);
            }
        });

        E_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_Count.setText("E Count");

        B4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B4.setText("E");

        A1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A1.setText("F");

        B5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B5.setText("G");

        B6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B6.setText("H");

        B7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B7.setText("I");

        B8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B8.setText("J");

        J_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        J_Value.setText("J");
        J_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_ValueActionPerformed(evt);
            }
        });

        I_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        I_Value.setText("I");
        I_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_ValueActionPerformed(evt);
            }
        });

        H_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H_Value.setText("H");
        H_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_ValueActionPerformed(evt);
            }
        });

        G_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        G_Value.setText("G");
        G_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_ValueActionPerformed(evt);
            }
        });

        F_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F_Value.setText("F");
        F_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_ValueActionPerformed(evt);
            }
        });

        F_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_Count.setText("F Count");

        G_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_Count.setText("G Count");

        H_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_Count.setText("H Count");

        I_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        I_Count.setText("I Count");

        J_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        J_Count.setText("J Count");

        A2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A2.setText("K");

        B9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B9.setText("L");

        B10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B10.setText("M");

        M_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        M_Value.setText("M");
        M_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_ValueActionPerformed(evt);
            }
        });

        L_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        L_Value.setText("L");
        L_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_ValueActionPerformed(evt);
            }
        });

        K_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        K_Value.setText("K");
        K_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_ValueActionPerformed(evt);
            }
        });

        K_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        K_Count.setText("K Count");

        L_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Count.setText("L Count");

        M_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        M_Count.setText("M Count");

        A4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A4.setText("N");

        B16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B16.setText("P");

        B15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B15.setText("O");

        B17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B17.setText("R");

        B18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B18.setText("S");

        A5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A5.setText("T");

        B19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B19.setText("U");

        B21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B21.setText("W");

        B20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B20.setText("V");

        B22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B22.setText("X");

        A6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A6.setText("Y");

        B23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B23.setText("Z");

        Z_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Z_Value.setText("Z");
        Z_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z_ValueActionPerformed(evt);
            }
        });

        Y_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Y_Value.setText("Y");
        Y_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y_ValueActionPerformed(evt);
            }
        });

        X_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        X_Value.setText("X");
        X_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X_ValueActionPerformed(evt);
            }
        });

        W_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        W_Value.setText("W");
        W_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W_ValueActionPerformed(evt);
            }
        });

        V_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V_Value.setText("V");
        V_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_ValueActionPerformed(evt);
            }
        });

        U_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        U_Value.setText("U");
        U_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_ValueActionPerformed(evt);
            }
        });

        T_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T_Value.setText("T");
        T_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_ValueActionPerformed(evt);
            }
        });

        S_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        S_Value.setText("S");
        S_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_ValueActionPerformed(evt);
            }
        });

        R_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        R_Value.setText("R");
        R_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_ValueActionPerformed(evt);
            }
        });

        P_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P_Value.setText("P");
        P_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_ValueActionPerformed(evt);
            }
        });

        O_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        O_Value.setText("O");
        O_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_ValueActionPerformed(evt);
            }
        });

        N_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        N_Value.setText("N");
        N_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_ValueActionPerformed(evt);
            }
        });

        N_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N_Count.setText("N Count");

        O_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        O_Count.setText("O Count");

        P_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P_Count.setText("P Count");

        R_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R_Count.setText("R Count");

        S_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        S_Count.setText("S Count");

        T_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_Count.setText("T Count");

        U_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_Count.setText("U Count");

        V_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        V_Count.setText("V Count");

        W_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        W_Count.setText("W Count");

        X_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X_Count.setText("X Count");

        Y_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Y_Count.setText("Y Count");

        Z_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Z_Count.setText("Z Count");

        B25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B25.setText("Q");

        Q_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Q_Value.setText("Q");
        Q_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q_ValueActionPerformed(evt);
            }
        });

        Q_Count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q_Count.setText("Q Count");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(A_Count)
                            .addComponent(A_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_Count)
                            .addComponent(B_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(C_Count)
                            .addComponent(C_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D_Count)
                            .addComponent(D_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(N_Count)
                            .addComponent(N_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(O_Count)
                            .addComponent(O_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P_Count)
                            .addComponent(P_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Q_Count)
                            .addComponent(Q_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B25, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(E_Count)
                            .addComponent(E_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(F_Count)
                            .addComponent(F_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(G_Count)
                            .addComponent(G_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(H_Count)
                            .addComponent(H_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(I_Count)
                            .addComponent(I_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(J_Count)
                            .addComponent(J_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(K_Count)
                            .addComponent(K_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(L_Count)
                            .addComponent(L_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M_Count)
                            .addComponent(M_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(R_Count)
                            .addComponent(R_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(S_Count)
                            .addComponent(S_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(T_Count)
                            .addComponent(T_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(U_Count)
                            .addComponent(U_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(V_Count)
                            .addComponent(V_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(W_Count)
                            .addComponent(W_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(X_Count)
                            .addComponent(X_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Y_Count)
                            .addComponent(Y_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Z_Count)
                            .addComponent(Z_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B23, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {A, A1, A2, A4, A5, A6, A_Count, A_Value, B1, B10, B15, B16, B17, B18, B19, B2, B20, B21, B22, B23, B25, B3, B4, B5, B6, B7, B8, B9, B_Count, B_Value, C_Count, C_Value, D_Count, D_Value, E_Count, E_Value, F_Count, F_Value, G_Count, G_Value, H_Count, H_Value, I_Count, I_Value, J_Count, J_Value, K_Count, K_Value, L_Count, L_Value, M_Count, M_Value, N_Count, N_Value, O_Count, O_Value, P_Count, P_Value, Q_Count, Q_Value, R_Count, R_Value, S_Count, S_Value, T_Count, T_Value, U_Count, U_Value, V_Count, V_Value, W_Count, W_Value, X_Count, X_Value, Y_Count, Y_Value, Z_Count, Z_Value});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(K_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(K_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(M_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(M_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(F_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(F_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(G_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(G_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(H_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(H_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(I_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(I_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(J_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(J_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(D_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(D_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(E_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(E_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Y_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Y_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Z_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Z_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(T_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(T_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(U_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(U_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(V_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(V_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(W_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(W_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(X_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(X_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(N_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(N_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(O_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(O_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(P_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(P_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(R_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(R_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(S_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(S_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(B25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabel3.setText("Encrypted Text");

        jLabel7.setText("Decrypted Text");

        DecryptedText.setColumns(20);
        DecryptedText.setRows(5);
        jScrollPane1.setViewportView(DecryptedText);

        EncryptedText.setColumns(20);
        EncryptedText.setRows(5);
        jScrollPane2.setViewportView(EncryptedText);

        SampleText.setColumns(20);
        SampleText.setRows(5);
        jScrollPane3.setViewportView(SampleText);

        jLabel8.setText("Sample Text");

        ReadSample.setText("Calculate from Sample");
        ReadSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadSampleActionPerformed(evt);
            }
        });

        Decrypt.setText("Decrypt");
        Decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecryptActionPerformed(evt);
            }
        });

        jButton1.setText("Letter Pairs Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        loadSampleText.setText("Load sample text");
        loadSampleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSampleTextActionPerformed(evt);
            }
        });
        fileMenu.add(loadSampleText);

        MenuBar.add(fileMenu);

        editMenu.setText("Edit");
        MenuBar.add(editMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(344, 344, 344)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReadSample)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Decrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Decrypt, ReadSample, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReadSample)
                    .addComponent(Decrypt)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_ValueActionPerformed
        highlight(A_Value.getText().charAt(0));
    }//GEN-LAST:event_A_ValueActionPerformed

    private void B_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ValueActionPerformed
        highlight(B_Value.getText().charAt(0));
    }//GEN-LAST:event_B_ValueActionPerformed

    private void C_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_ValueActionPerformed
        highlight(C_Value.getText().charAt(0));
    }//GEN-LAST:event_C_ValueActionPerformed

    private void D_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_ValueActionPerformed
        highlight(D_Value.getText().charAt(0));
    }//GEN-LAST:event_D_ValueActionPerformed

    private void E_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_ValueActionPerformed
        highlight(E_Value.getText().charAt(0));
    }//GEN-LAST:event_E_ValueActionPerformed

    private void J_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_ValueActionPerformed
        highlight(J_Value.getText().charAt(0));
    }//GEN-LAST:event_J_ValueActionPerformed

    private void I_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_ValueActionPerformed
        highlight(I_Value.getText().charAt(0));
    }//GEN-LAST:event_I_ValueActionPerformed

    private void H_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_ValueActionPerformed
        highlight(H_Value.getText().charAt(0));
    }//GEN-LAST:event_H_ValueActionPerformed

    private void G_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_ValueActionPerformed
        highlight(G_Value.getText().charAt(0));
    }//GEN-LAST:event_G_ValueActionPerformed

    private void F_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_ValueActionPerformed
        highlight(F_Value.getText().charAt(0));
    }//GEN-LAST:event_F_ValueActionPerformed

    private void M_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_ValueActionPerformed
        highlight(M_Value.getText().charAt(0));
    }//GEN-LAST:event_M_ValueActionPerformed

    private void L_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_ValueActionPerformed
        highlight(L_Value.getText().charAt(0));
    }//GEN-LAST:event_L_ValueActionPerformed

    private void K_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K_ValueActionPerformed
        highlight(K_Value.getText().charAt(0));
    }//GEN-LAST:event_K_ValueActionPerformed

    private void Z_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z_ValueActionPerformed
        highlight(Z_Value.getText().charAt(0));
    }//GEN-LAST:event_Z_ValueActionPerformed

    private void Y_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y_ValueActionPerformed
        highlight(Y_Value.getText().charAt(0));
    }//GEN-LAST:event_Y_ValueActionPerformed

    private void X_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X_ValueActionPerformed
        highlight(X_Value.getText().charAt(0));
    }//GEN-LAST:event_X_ValueActionPerformed

    private void W_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W_ValueActionPerformed
        highlight(W_Value.getText().charAt(0));
    }//GEN-LAST:event_W_ValueActionPerformed

    private void V_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_ValueActionPerformed
        highlight(V_Value.getText().charAt(0));
    }//GEN-LAST:event_V_ValueActionPerformed

    private void U_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_ValueActionPerformed
        highlight(U_Value.getText().charAt(0));
    }//GEN-LAST:event_U_ValueActionPerformed

    private void T_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_ValueActionPerformed
        highlight(T_Value.getText().charAt(0));
    }//GEN-LAST:event_T_ValueActionPerformed

    private void S_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_ValueActionPerformed
        highlight(S_Value.getText().charAt(0));
    }//GEN-LAST:event_S_ValueActionPerformed

    private void R_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_ValueActionPerformed
        highlight(R_Value.getText().charAt(0));
    }//GEN-LAST:event_R_ValueActionPerformed

    private void P_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_ValueActionPerformed
        highlight(P_Value.getText().charAt(0));
    }//GEN-LAST:event_P_ValueActionPerformed

    private void O_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_ValueActionPerformed
        highlight(O_Value.getText().charAt(0));
    }//GEN-LAST:event_O_ValueActionPerformed

    private void N_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_ValueActionPerformed
        highlight(N_Value.getText().charAt(0));
    }//GEN-LAST:event_N_ValueActionPerformed

    private void Q_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q_ValueActionPerformed
        highlight(Q_Value.getText().charAt(0));
    }//GEN-LAST:event_Q_ValueActionPerformed

    
    CharCount[] getLetterFrequency(String text) {
        CharCount letterCount[] = new CharCount[26];
         
        text = text.toUpperCase();
        
        for(int j = 0; j < 26; j++) {
            letterCount[j] = new CharCount((char)(65 + j));
        }
        
        for(int i = 0; i < text.length(); i++) {
            char curChar = text.charAt(i);
            //curChar = Character.toUpperCase(curChar);
            int value = (int)curChar;
            value = value - 65;
            if(value >= 0 && value <= 25) {
                letterCount[value].increment();
            }
        }
        
        return letterCount;
        
    }
    
    CharCount[] sortCharCount(CharCount[] input) {
        Arrays.sort(input);
        return input;
    }
    
    private void highlight(char curChar) {
      Highlighter h = DecryptedText.getHighlighter();
      h.removeAllHighlights();
      String text = DecryptedText.getText().toUpperCase();

      Highlighter.HighlightPainter yellowPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.yellow);
      
      for (int j = 0; j < text.length(); j += 1) {
        char ch = text.charAt(j);
        if (ch == curChar) {
            try {
                h.addHighlight(j, j + 1, yellowPainter/*DefaultHighlighter.DefaultPainter*/);
                
            } catch (BadLocationException e) {
            }
        }
      }
    }
    public void changeTextBox() {
        /*switch(encrypted) {
            case 'A': 
                A_Value.setText(Character.toString(cipher));
                break;
                
        }*/
        A_Value.setText(Character.toString(decryptKey.get('A')));
        B_Value.setText(Character.toString(decryptKey.get('B')));
        C_Value.setText(Character.toString(decryptKey.get('C')));
        D_Value.setText(Character.toString(decryptKey.get('D')));
        E_Value.setText(Character.toString(decryptKey.get('E')));
        F_Value.setText(Character.toString(decryptKey.get('F')));
        G_Value.setText(Character.toString(decryptKey.get('G')));
        H_Value.setText(Character.toString(decryptKey.get('H')));
        I_Value.setText(Character.toString(decryptKey.get('I')));
        J_Value.setText(Character.toString(decryptKey.get('J')));
        K_Value.setText(Character.toString(decryptKey.get('K')));
        L_Value.setText(Character.toString(decryptKey.get('L')));
        M_Value.setText(Character.toString(decryptKey.get('M')));
        N_Value.setText(Character.toString(decryptKey.get('N')));
        O_Value.setText(Character.toString(decryptKey.get('O')));
        P_Value.setText(Character.toString(decryptKey.get('P')));
        Q_Value.setText(Character.toString(decryptKey.get('Q')));
        R_Value.setText(Character.toString(decryptKey.get('R')));
        S_Value.setText(Character.toString(decryptKey.get('S')));
        T_Value.setText(Character.toString(decryptKey.get('T')));
        U_Value.setText(Character.toString(decryptKey.get('U')));
        V_Value.setText(Character.toString(decryptKey.get('V')));
        W_Value.setText(Character.toString(decryptKey.get('W')));
        X_Value.setText(Character.toString(decryptKey.get('X')));
        Y_Value.setText(Character.toString(decryptKey.get('Y')));
        Z_Value.setText(Character.toString(decryptKey.get('Z')));
        
    }
    
    private void ReadSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadSampleActionPerformed
        // TODO add your handling code here:
        
        sampleText += SampleText.getText();
        sampleFrequency = getLetterFrequency(sampleText);
        
        encryptedText = EncryptedText.getText();
        encryptedFrequency = getLetterFrequency(encryptedText);
       
        
        A_Count.setText(Integer.toString(encryptedFrequency[0].getCountValue()));
        B_Count.setText(Integer.toString(encryptedFrequency[1].getCountValue()));
        C_Count.setText(Integer.toString(encryptedFrequency[2].getCountValue()));
        D_Count.setText(Integer.toString(encryptedFrequency[3].getCountValue()));
        E_Count.setText(Integer.toString(encryptedFrequency[4].getCountValue()));
        F_Count.setText(Integer.toString(encryptedFrequency[5].getCountValue()));
        G_Count.setText(Integer.toString(encryptedFrequency[6].getCountValue()));
        H_Count.setText(Integer.toString(encryptedFrequency[7].getCountValue()));
        I_Count.setText(Integer.toString(encryptedFrequency[8].getCountValue()));
        J_Count.setText(Integer.toString(encryptedFrequency[9].getCountValue()));
        K_Count.setText(Integer.toString(encryptedFrequency[10].getCountValue()));
        L_Count.setText(Integer.toString(encryptedFrequency[11].getCountValue()));
        M_Count.setText(Integer.toString(encryptedFrequency[12].getCountValue()));
        N_Count.setText(Integer.toString(encryptedFrequency[13].getCountValue()));
        O_Count.setText(Integer.toString(encryptedFrequency[14].getCountValue()));
        P_Count.setText(Integer.toString(encryptedFrequency[15].getCountValue()));
        Q_Count.setText(Integer.toString(encryptedFrequency[16].getCountValue()));
        R_Count.setText(Integer.toString(encryptedFrequency[17].getCountValue()));
        S_Count.setText(Integer.toString(encryptedFrequency[18].getCountValue()));
        T_Count.setText(Integer.toString(encryptedFrequency[19].getCountValue()));
        U_Count.setText(Integer.toString(encryptedFrequency[20].getCountValue()));
        V_Count.setText(Integer.toString(encryptedFrequency[21].getCountValue()));
        W_Count.setText(Integer.toString(encryptedFrequency[22].getCountValue()));
        X_Count.setText(Integer.toString(encryptedFrequency[23].getCountValue()));
        Y_Count.setText(Integer.toString(encryptedFrequency[24].getCountValue()));
        Z_Count.setText(Integer.toString(encryptedFrequency[25].getCountValue()));
        
        sortCharCount(sampleFrequency);
        sortCharCount(encryptedFrequency);
        
        for(int i = 0; i < 26; i++) {
            //decryptKey.put(sampleFrequency[i].getCharValue(), encryptedFrequency[i].getCharValue());
            decryptKey.put(encryptedFrequency[i].getCharValue(), sampleFrequency[i].getCharValue());
        }
        decryptKey.put(' ', ' ');
        decryptKey.put('\n', '\n');
        
        changeTextBox();
        
    }//GEN-LAST:event_ReadSampleActionPerformed

    
    
    private void DecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecryptActionPerformed
       
        decryptKey.replace('A', A_Value.getText().charAt(0));
        decryptKey.replace('B', B_Value.getText().charAt(0));
        decryptKey.replace('C', C_Value.getText().charAt(0));
        decryptKey.replace('D', D_Value.getText().charAt(0));
        decryptKey.replace('E', E_Value.getText().charAt(0));
        decryptKey.replace('F', F_Value.getText().charAt(0));
        decryptKey.replace('G', G_Value.getText().charAt(0));
        decryptKey.replace('H', H_Value.getText().charAt(0));
        decryptKey.replace('I', I_Value.getText().charAt(0));
        decryptKey.replace('J', J_Value.getText().charAt(0));
        decryptKey.replace('K', K_Value.getText().charAt(0));
        decryptKey.replace('L', L_Value.getText().charAt(0));
        decryptKey.replace('M', M_Value.getText().charAt(0));
        decryptKey.replace('N', N_Value.getText().charAt(0));
        decryptKey.replace('O', O_Value.getText().charAt(0));
        decryptKey.replace('P', P_Value.getText().charAt(0));
        decryptKey.replace('Q', Q_Value.getText().charAt(0));
        decryptKey.replace('R', R_Value.getText().charAt(0));
        decryptKey.replace('S', S_Value.getText().charAt(0));
        decryptKey.replace('T', T_Value.getText().charAt(0));
        decryptKey.replace('U', U_Value.getText().charAt(0));
        decryptKey.replace('V', V_Value.getText().charAt(0));
        decryptKey.replace('W', W_Value.getText().charAt(0));
        decryptKey.replace('X', X_Value.getText().charAt(0));
        decryptKey.replace('Y', Y_Value.getText().charAt(0));
        decryptKey.replace('Z', Z_Value.getText().charAt(0));

        
        
        
        
        
        String decryptedText = "";

        for(int i = 0; i < encryptedText.length(); i++) {
            decryptedText += decryptKey.get(encryptedText.charAt(i));
        }
        
        DecryptedText.setText(decryptedText);
        
    }//GEN-LAST:event_DecryptActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void loadSampleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSampleTextActionPerformed
        sampleText = "";
        FileNameExtensionFilter filter = new FileNameExtensionFilter("text files", "txt", "text");
        jFileChooser.setFileFilter(filter);
        jFileChooser.showOpenDialog(P_Count);

        File file =jFileChooser.getSelectedFile();
        sampleText += file.toString();
    }//GEN-LAST:event_loadSampleTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Scanner scan = new Scanner(sampleText);
        while(scan.hasNext()){
            String word = scan.next();
            for (int i = 1; i < word.length(); i++) {
                //maybe rework this to not use a map and use something else
                String pair= word.substring(i-1, i+1);
                if(!samplePairFrequency.containsKey(pair)){
                    samplePairFrequency.put(pair, 1);
                }
                else{
                    int count=samplePairFrequency.get(pair);
                    samplePairFrequency.replace(pair, count++);
                    
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonoAlphabetCrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonoAlphabetCrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonoAlphabetCrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonoAlphabetCrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonoAlphabetCrypto().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A_Count;
    private javax.swing.JTextField A_Value;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B10;
    private javax.swing.JLabel B15;
    private javax.swing.JLabel B16;
    private javax.swing.JLabel B17;
    private javax.swing.JLabel B18;
    private javax.swing.JLabel B19;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B20;
    private javax.swing.JLabel B21;
    private javax.swing.JLabel B22;
    private javax.swing.JLabel B23;
    private javax.swing.JLabel B25;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel B9;
    private javax.swing.JLabel B_Count;
    private javax.swing.JTextField B_Value;
    private javax.swing.JLabel C_Count;
    private javax.swing.JTextField C_Value;
    private javax.swing.JLabel D_Count;
    private javax.swing.JTextField D_Value;
    private javax.swing.JButton Decrypt;
    private javax.swing.JTextArea DecryptedText;
    private javax.swing.JLabel E_Count;
    private javax.swing.JTextField E_Value;
    private javax.swing.JTextArea EncryptedText;
    private javax.swing.JLabel F_Count;
    private javax.swing.JTextField F_Value;
    private javax.swing.JLabel G_Count;
    private javax.swing.JTextField G_Value;
    private javax.swing.JLabel H_Count;
    private javax.swing.JTextField H_Value;
    private javax.swing.JLabel I_Count;
    private javax.swing.JTextField I_Value;
    private javax.swing.JLabel J_Count;
    private javax.swing.JTextField J_Value;
    private javax.swing.JLabel K_Count;
    private javax.swing.JTextField K_Value;
    private javax.swing.JLabel L_Count;
    private javax.swing.JTextField L_Value;
    private javax.swing.JLabel M_Count;
    private javax.swing.JTextField M_Value;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel N_Count;
    private javax.swing.JTextField N_Value;
    private javax.swing.JLabel O_Count;
    private javax.swing.JTextField O_Value;
    private javax.swing.JLabel P_Count;
    private javax.swing.JTextField P_Value;
    private javax.swing.JLabel Q_Count;
    private javax.swing.JTextField Q_Value;
    private javax.swing.JLabel R_Count;
    private javax.swing.JTextField R_Value;
    private javax.swing.JButton ReadSample;
    private javax.swing.JLabel S_Count;
    private javax.swing.JTextField S_Value;
    private javax.swing.JTextArea SampleText;
    private javax.swing.JLabel T_Count;
    private javax.swing.JTextField T_Value;
    private javax.swing.JLabel U_Count;
    private javax.swing.JTextField U_Value;
    private javax.swing.JLabel V_Count;
    private javax.swing.JTextField V_Value;
    private javax.swing.JLabel W_Count;
    private javax.swing.JTextField W_Value;
    private javax.swing.JLabel X_Count;
    private javax.swing.JTextField X_Value;
    private javax.swing.JLabel Y_Count;
    private javax.swing.JTextField Y_Value;
    private javax.swing.JLabel Z_Count;
    private javax.swing.JTextField Z_Value;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem loadSampleText;
    // End of variables declaration//GEN-END:variables
}
